project:
  type: book
  output-dir: docs

book:
  title: "MATH 125 --<br>Quantitative Reasoning"
  author: "Colton Gearhart"
  date: "2-2-2024"
  cover-image: quantitative-reasoning.png
  chapters:
    - index.qmd
    - syllabus.qmd

    - part: chapter-finance.qmd
      chapters:
        - finance-using-percentages.qmd
        - finance-understanding-interest.qmd
        - finance-saving-and-investing.qmd
        - finance-borrowing-money.qmd
        - finance-budgeting.qmd
        - finance-review.qmd

    - part: chapter-prob.qmd
      chapters:
        - prob-intro-to-probability.qmd
        - prob-counting-outcomes.qmd
        - prob-probability-of-single-events.qmd
        - prob-addition-and-multiplication-rules.qmd
        - prob-expected-value.qmd
        - prob-review.qmd

    - part: chapter-stats.qmd
      chapters:
        - stats-statistical-studies.qmd
        - stats-displaying-data.qmd
        - stats-describing-and-analyzing-data.qmd
        - stats-the-normal-distribution.qmd
        - stats-confidence-intervals.qmd
        - stats-data-exploration.qmd
        - stats-project.qmd
        - stats-review.qmd

format:
  html:
    theme: flatly

title-block-banner: true
