project:
  type: book
  output-dir: docs

book:
  title: "MATH 125 --<br>Quantitative Reasoning"
  author: "Colton Gearhart"
  date: "11-1-2023"
  cover-image: quantitative-reasoning.png
  chapters:
    - index.qmd
    - syllabus.qmd

    - part: chapter-finance.qmd
      chapters:
        - finance-understanding-personal-finance.qmd
        - finance-understanding-interest.qmd
        - finance-saving-money.qmd
        - finance-borrowing-money.qmd
        - finance-review.qmd

    - part: chapter-prob.qmd
      chapters:
        - prob-intro-to-probability.qmd
        - prob-counting-to-probabilities.qmd
        - prob-using-counting-methods-to-find-probabilities.qmd
        - prob-addition-and-multiplication-rules.qmd
        - prob-expected-value.qmd
        - prob-review.qmd

    - part: chapter-stats.qmd
      chapters:
        - stats-collecting-data.qmd
        - stats-displaying-data.qmd
        - stats-describing-and-analyzing-data.qmd
        - stats-normal-distribution.qmd
        - stats-linear-regression.qmd
        - stats-project.qmd
        - stats-review.qmd

format:
  html:
    theme: flatly

title-block-banner: true
